In [ ]:

from __future__ import annotations

import os
import pathlib
import sys

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from dotenv import load_dotenv
from sqlalchemy import create_engine
from tqdm import tqdm

ROOT = "f:\\Document\\GitHub\\Multistrat"
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
load_dotenv(ROOT + "\\.env")

True

# Data

In [4]:
# Format for PostgreSQL URL:
# postgresql://username:password@host:port/database
#
# Example for another device in the same network (replace values as needed):
# host = IP address of the database device, e.g. 192.168.1.42

#database_url = os.getenv("DATABASE_URL")
database_url = "postgresql://multistrat:changeme@192.168.1.249:5432/multistrat"
# Set DATABASE_URL in your .env or environment to the correct value as above

#if not database_url:
#    raise ValueError("DATABASE_URL is not set. Add it to .env or environment variables.")

engine = create_engine(database_url)

# Query to get all table names in the public schema
tables_df = pd.read_sql(
    """
    SELECT table_name
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_type = 'BASE TABLE';
    """,
    engine
)
print(tables_df)

                      table_name
0                alembic_version
1                         orders
2                       accounts
3                       balances
4                        symbols
5                balance_changes
6                      positions
7                         assets
8                          ohlcv
9               ingestion_cursor
10                    basis_rate
11                  basis_cursor
12                 open_interest
13          open_interest_cursor
14         taker_buy_sell_volume
15  taker_buy_sell_volume_cursor
16         top_trader_long_short
17  top_trader_long_short_cursor
18                scheduler_runs

In [21]:
basis = pd.read_sql(
    """
    select 
        pair as symbol,
        sample_time as ts,
        basis * 100 / index_price as basis_rate
    from basis_rate
    where period = '1h' and contract_type = 'PERPETUAL'
    ;
    """,
    engine
)

In [23]:
open_interest = pd.read_sql(
    """
    select
        symbol as symbol,
        sample_time as ts,
        sum_open_interest as open_interest,
        sum_open_interest_value as open_interest_value,
        cmc_circulating_supply as cmc_circulating_supply
    from open_interest
    where period = '1h' and contract_type = 'PERPETUAL'
    """,
    engine
)

In [ ]:
pd.read_sql(
    """
    select
        *
    from            
    where period = '1h'
    """,
    engine
)

,symbol,period,sample_time,buy_sell_ratio,buy_vol,sell_vol,ingested_at
0,BTCUSDT,1h,2026-02-26 21:00:00+00:00,0.9106,1550.175,1702.454,2026-03-25 21:52:02.325701+00:00
1,BTCUSDT,1h,2026-02-26 22:00:00+00:00,0.9106,1026.708,1127.555,2026-03-25 21:52:02.325701+00:00
2,BTCUSDT,1h,2026-02-26 23:00:00+00:00,0.9049,1213.712,1341.329,2026-03-25 21:52:02.325701+00:00
3,BTCUSDT,1h,2026-02-27 00:00:00+00:00,0.8461,2514.331,2971.588,2026-03-25 21:52:02.325701+00:00
4,BTCUSDT,1h,2026-02-27 01:00:00+00:00,0.8857,3562.664,4022.333,2026-03-25 21:52:02.325701+00:00
...,...,...,...,...,...,...,...
55687,TONUSDT,1h,2026-04-10 22:00:00+00:00,1.1480,265482.600,231264.700,2026-04-12 21:00:42.586604+00:00
55688,TAOUSDT,1h,2026-04-10 22:00:00+00:00,0.7710,39398.442,51101.643,2026-04-12 21:00:42.588898+00:00
55689,TAOUSDT,1h,2026-04-10 10:00:00+00:00,1.1058,85052.878,76915.667,2026-04-12 09:00:14.516369+00:00
55690,TONUSDT,1h,2026-04-10 18:00:00+00:00,0.8829,242683.300,274873.700,2026-04-12 17:00:37.466296+00:00
55691,TAOUSDT,1h,2026-04-11 02:00:00+00:00,1.1547,37869.054,32796.803,2026-04-13 01:00:37.752396+00:00

In [5]:
ohlcv_df = pd.read_sql(
    """
    select 
        open_time as ts,
        symbol,
        open as open,
        high as high,
        low as low,
        close as close,
        volume as volume,
        quote_volume as quote_volume
    from ohlcv
    where interval = '1h' and open_time <= '2024-01-01'
    ;
    """,
    engine
)
print(ohlcv_df)

         symbol interval                 open_time   open   high    low  \
0       FILUSDT       1h 2021-11-07 20:00:00+00:00  62.33  62.59  62.15
1       FILUSDT       1h 2021-11-07 21:00:00+00:00  62.55  62.61  62.39
2       FILUSDT       1h 2021-11-07 22:00:00+00:00  62.47  62.56  62.17
3       FILUSDT       1h 2021-11-07 23:00:00+00:00  62.38  62.56  62.20
4       FILUSDT       1h 2021-11-08 00:00:00+00:00  62.56  63.80  62.34
...         ...      ...                       ...    ...    ...    ...
805294  FILUSDT       1h 2021-11-07 15:00:00+00:00  62.04  62.19  61.70
805295  FILUSDT       1h 2021-11-07 16:00:00+00:00  62.11  62.50  61.90
805296  FILUSDT       1h 2021-11-07 17:00:00+00:00  62.18  62.38  61.97
805297  FILUSDT       1h 2021-11-07 18:00:00+00:00  62.06  62.23  61.96
805298  FILUSDT       1h 2021-11-07 19:00:00+00:00  62.12  62.49  62.06

        close     volume  quote_volume  trades  \
0       62.55   77250.47  4.819704e+06    5925
1       62.47   71843.99  4.489458e+06    5034
2       62.37   79178.22  4.936174e+06    5538
3       62.56   75852.30  4.729835e+06    4891
4       63.45  350215.49  2.205519e+07   29414
...       ...        ...           ...     ...
805294  62.11  110270.37  6.836446e+06    7062
805295  62.19  154668.20  9.611367e+06    9656
805296  62.07   77843.92  4.836762e+06    5855
805297  62.12   72200.71  4.481193e+06    5341
805298  62.33   70942.96  4.415522e+06    5340

                             close_time                      ingested_at
0      2021-11-07 20:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
1      2021-11-07 21:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
2      2021-11-07 22:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
3      2021-11-07 23:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
4      2021-11-08 00:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
...                                 ...                              ...
805294 2021-11-07 15:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
805295 2021-11-07 16:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
805296 2021-11-07 17:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
805297 2021-11-07 18:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00
805298 2021-11-07 19:59:59.999000+00:00 2026-03-25 21:47:37.692600+00:00

[805299 rows x 12 columns]

# Research

In [3]:
df

,ts,symbol,open,high,low,close,volume,quote_volume
0,2021-03-27 04:00:00+00:00,BNBUSDT,252.1205,254.6259,251.9193,253.3218,85350.0930,2.162363e+07
1,2021-03-27 05:00:00+00:00,BNBUSDT,253.3217,254.2310,251.8653,253.1652,67508.0790,1.708696e+07
2,2021-03-27 06:00:00+00:00,BNBUSDT,253.1821,254.3546,252.7001,253.5722,71666.3850,1.817010e+07
3,2021-03-27 07:00:00+00:00,BNBUSDT,253.5704,253.9376,251.4125,252.4047,79425.0300,2.007825e+07
4,2021-03-27 08:00:00+00:00,BNBUSDT,252.4047,256.0000,251.7391,255.6644,116633.5730,2.958796e+07
...,...,...,...,...,...,...,...,...
805294,2023-12-31 20:00:00+00:00,ETHUSDT,2294.8300,2294.8300,2280.2800,2282.4000,12876.9660,2.944690e+07
805295,2023-12-31 21:00:00+00:00,ETHUSDT,2282.4000,2292.7500,2280.1100,2283.2000,7392.8667,1.690656e+07
805296,2023-12-31 22:00:00+00:00,ETHUSDT,2283.2100,2293.9900,2258.8800,2274.7700,18374.1473,4.184334e+07
805297,2023-12-31 23:00:00+00:00,ETHUSDT,2274.7600,2284.4200,2272.4900,2281.8700,10288.4085,2.345258e+07
805298,2024-01-01 00:00:00+00:00,ETHUSDT,2281.8700,2297.1800,2281.2700,2295.5100,10771.9183,2.468757e+07